import Head from "next/head";
import Nav from "../src/components/Nav";

export default function Home() {
  return (
    <>
      <Nav />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </>
  );
}
